spring.application.name=securevault

spring.datasource.url=jdbc:postgresql://localhost:5432/securevault
spring.datasource.username=postgres
spring.datasource.password=Jyo13@postgresql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true