// ---------------------------------------------------------------------------
// Mock data used only for front-end development, before the Spring Boot
// endpoints are wired up. Every mock export is prefixed with `mock` so it's
// easy to grep for and delete once real API calls replace it.
// ---------------------------------------------------------------------------

export const mockCategories = [
  "PERSONAL",
  "WORK",
  "DEVELOPMENT",
  "SOCIAL",
  "BANKING",
  "ENTERTAINMENT",
  "OTHER",
];

export const mockCredentials = [
  {
    id: "1",
    title: "Google Account",
    username: "arjun.rao@gmail.com",
    password: "Kx9!mQ2vLp#8Rw",
    url: "https://accounts.google.com",
    category: "PERSONAL",
    notes: "Recovery email tied to work accounts.",
    strength: "strong",
    favorite: true,
    createdAt: "2026-05-02T10:12:00Z",
    updatedAt: "2026-07-14T09:00:00Z",
  },
  {
    id: "2",
    title: "GitHub",
    username: "arjunrao-dev",
    password: "gh_7fT!qX2z",
    url: "https://github.com",
    category: "DEVELOPMENT",
    notes: "2FA enabled via authenticator app.",
    strength: "strong",
    favorite: true,
    createdAt: "2026-04-20T14:30:00Z",
    updatedAt: "2026-04-20T14:30:00Z",
  },
  {
    id: "3",
    title: "Microsoft 365",
    username: "arjun.rao@outlook.com",
    password: "Winter2024",
    url: "https://microsoft.com",
    category: "WORK",
    notes: "",
    strength: "weak",
    favorite: false,
    createdAt: "2026-03-11T08:00:00Z",
    updatedAt: "2026-06-01T11:20:00Z",
  },
  {
    id: "4",
    title: "Amazon",
    username: "arjun.rao@gmail.com",
    password: "Am@zon#Shop2025!",
    url: "https://amazon.com",
    category: "PERSONAL",
    notes: "Prime membership.",
    strength: "strong",
    favorite: false,
    createdAt: "2026-02-18T16:45:00Z",
    updatedAt: "2026-02-18T16:45:00Z",
  },
  {
    id: "5",
    title: "LinkedIn",
    username: "arjun.rao",
    password: "linkedin123",
    url: "https://linkedin.com",
    category: "SOCIAL",
    notes: "",
    strength: "weak",
    favorite: false,
    createdAt: "2026-01-30T09:15:00Z",
    updatedAt: "2026-01-30T09:15:00Z",
  },
  {
    id: "6",
    title: "Netflix",
    username: "arjun.rao@gmail.com",
    password: "N3tfl!xNight$",
    url: "https://netflix.com",
    category: "ENTERTAINMENT",
    notes: "Shared with family plan.",
    strength: "medium",
    favorite: false,
    createdAt: "2025-12-05T20:00:00Z",
    updatedAt: "2025-12-05T20:00:00Z",
  },
  {
    id: "7",
    title: "HDFC Net Banking",
    username: "arao_hdfc",
    password: "B@nk!ng#Secure99",
    url: "https://netbanking.hdfcbank.com",
    category: "BANKING",
    notes: "Uses hardware OTP token.",
    strength: "strong",
    favorite: true,
    createdAt: "2025-11-22T07:40:00Z",
    updatedAt: "2026-06-30T12:00:00Z",
  },
  {
    id: "8",
    title: "College Portal",
    username: "22CS1042",
    password: "college@2022",
    url: "https://portal.college.edu",
    category: "OTHER",
    notes: "",
    strength: "medium",
    favorite: false,
    createdAt: "2025-09-01T09:00:00Z",
    updatedAt: "2025-09-01T09:00:00Z",
  },
];

export const mockDashboardStats = {
  totalCredentials: mockCredentials.length,
  strongPasswords: mockCredentials.filter((c) => c.strength === "strong").length,
  weakPasswords: mockCredentials.filter((c) => c.strength === "weak").length,
  recentlyAdded: 3,
  securityScore: 78,
};

export const mockActivity = [
  {
    id: "a1",
    type: "created",
    message: "Created credential \"Netflix\"",
    timestamp: "2026-08-14T18:22:00Z",
  },
  {
    id: "a2",
    type: "updated",
    message: "Updated password for \"HDFC Net Banking\"",
    timestamp: "2026-08-13T09:05:00Z",
  },
  {
    id: "a3",
    type: "login",
    message: "Signed in from a new device",
    timestamp: "2026-08-12T21:47:00Z",
  },
  {
    id: "a4",
    type: "deleted",
    message: "Moved \"Old Work Email\" to Trash",
    timestamp: "2026-08-10T15:10:00Z",
  },
];
